### ISSUE TITLE
Exception on paging through selection

### ISSUE THREAD

**Issue by Stullemon** [OneDrive/onedrive-sdk-python#22] opened 2016-02-24 14:38 UTC
I am still working on my backup script (see #21 ). As one would expect, I am recursively looping through the various directories in the directory structure (rather deep structures, up to approx. 10 levels with between 1 and a couple of hundred files per directory). Now, I ran into an issue where I am trying to get a collection page and the json decoder throws an exception. Some more trial and error eventually got me to realize that the supposed json-string for decoding is actually empty. Here is the call stack followed by the line which throws the error (please ignore my crude style of coding).

```
Traceback (most recent call last):

  File "<ipython-input-14-f4000242bd12>", line 1, in <module>
    debugfile('F:/IWU/Python_new/OneDriveUpdate.py', wdir='F:/IWU/Python_new')

  File "F:\Software\WinPython\python-3.4.3.amd64\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 808, in debugfile
    debugger.run("runfile(%r, args=%r, wdir=%r)" % (filename, args, wdir))

  File "F:\Software\WinPython\python-3.4.3.amd64\lib\bdb.py", line 431, in run
    exec(cmd, globals, locals)

  File "<string>", line 1, in <module>

  File "F:\Software\WinPython\python-3.4.3.amd64\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 786, in runfile
    execfile(filename, namespace)

  File "F:\Software\WinPython\python-3.4.3.amd64\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 87, in execfile
    exec(compile(open(filename, 'rb').read(), filename, 'exec'), namespace)

  File "f:/iwu/python_new/onedriveupdate.py", line 553, in <module>
    if not checkDirContent(rootDir, upDirID, posFilter):

  File "f:/iwu/python_new/onedriveupdate.py", line 278, in checkDirContent
    if not checkDirContent(localItem['path'], dirID, None, (localItem['name'] == 'Zotero'), (defaultDelete and localItem['name'] == 'storage')):

  File "f:/iwu/python_new/onedriveupdate.py", line 278, in checkDirContent
    if not checkDirContent(localItem['path'], dirID, None, (localItem['name'] == 'Zotero'), (defaultDelete and localItem['name'] == 'storage')):

  File "f:/iwu/python_new/onedriveupdate.py", line 241, in checkDirContent
    upParentItemsList = getParentItemsList(upParentDirID,dirPath)

  File "f:/iwu/python_new/onedriveupdate.py", line 100, in getParentItemsList
    upParentItemsList.append(client.item(id=str(upParentDirID)).children.request().get())

  File "F:\Software\WinPython\python-3.4.3.amd64\lib\site-packages\onedrivesdk\request\children_collection.py", line 90, in get
    collection_response = ChildrenCollectionResponse(json.loads(self.send().content))

  File "F:\Software\WinPython\python-3.4.3.amd64\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)

  File "F:\Software\WinPython\python-3.4.3.amd64\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "F:\Software\WinPython\python-3.4.3.amd64\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None

ValueError: Expecting value: line 1 column 1 (char 0)
```

The code (the essential bit; note I am creating a list of pages to retrieve all items, not just 200, for later use) --> second row causes exception:

```
        upItemsList = []
        upItemsList.append(client.item(id=str(upParentDirID)).children.request().get())
        while len(upParentItemsList[i]) == 200 and len(upParentItemsList[i]) != 0:
            # Loop while the count is 200 (last one will have less)
            upParentItemsList.append(upParentItemsList[i].next_page_request.get())
            i += 1
```

Eventual function which crashes is:

```
    def raw_decode(self, s, idx=0):
        """Decode a JSON document from ``s`` (a ``str`` beginning with
        a JSON document) and return a 2-tuple of the Python
        representation and the index in ``s`` where the document ended.

        This can be used to decode a JSON document from a string that may
        have extraneous data at the end.

        """
        try:
            obj, end = self.scan_once(s, idx)
        except StopIteration as err:
            raise ValueError(errmsg("Expecting value", s, err.value)) from None
        return obj, end
```

I hope this helps - and it's not really my fault to begin with.

**Comment by cdmayer** [comment] 2016-02-24 17:21
It's hard to debug with the information you have here. Can you do me a favor and follow these steps?
- Open F:\Software\WinPython\python-3.4.3.amd64\Lib\site-packages\onedrivesdk\http_provider.py
- In `send` add these new lines:

``` python
    ...    
        else:
            request = requests.Request(method,
                                       url,
                                       headers=headers,
                                       data=data,
                                       json=content)
            prepped = request.prepare()
            response = session.send(prepped)

        #Add these
        new_headers = dict(headers)
        if 'Authorization' in new_headers:
            del new_headers['Authorization']
        print(method, new_headers, url, data, content, sep='\n')
    ...
```
- Re-run your code
- Send me the info printed to your console.

This should give me some more insight into the issue. Afterwords, you can delete the added lines so that you don't get junk printed to your console every time you use the SDK.

**Comment by Stullemon** [comment] 2016-02-25 07:04
Hey Chris,

I messed up at first and forgot the "new_headers = dict(headers)" line, so I replaced "new_headers" with "headers" in the following lines. I.e.:

```
        if 'Authorization' in headers:
            del headers['Authorization']
        print(method, headers, url, data, content, sep='\n')
```

After a number of successful listings, this yielded another error, just as yesterday. Note, I was using Spyder's debugging mode to be made aware when the issue occurred. This is the log (both first and second attempt to list directory):

```
GET
{'X-RequestStats': 'SDK-Version=python-v1.0.1'}
https://api.onedrive.com/v1.0/drive/items/93778B57A564E317!4120/children
None
None
Unknown Error: Failed to list directory: \Literatur\Conference.Proceedings\ASIM_SPL2013 --> Trying again.
> f:\iwu\python_new\onedriveupdate.py(120)getUpItemsList()
    119         L.printL('Unknown Error: Failed to list directory: {0} --> Trying again.'.format(dirPath[(len(rootDir)-len(dirPath)):]))
1-> 120         upItemsList = getUpItemsList(upParentDirID, dirPath, attempt+1)
    121     L.printL('List directory: {0} --> {1} pages'.format(dirPath[(len(rootDir)-len(dirPath)):],len(upItemsList)),False)

GET
{'X-RequestStats': 'SDK-Version=python-v1.0.1'}
https://api.onedrive.com/v1.0/drive/items/93778B57A564E317!4120/children
None
None
> f:\iwu\python_new\onedriveupdate.py(121)getUpItemsList()
1   120         upItemsList = getUpItemsList(upParentDirID, dirPath, attempt+1)
--> 121     L.printL('List directory: {0} --> {1} pages'.format(dirPath[(len(rootDir)-len(dirPath)):],len(upItemsList)),False)
    122     return upItemsList
```

Sure enough I noticed my error, and added the code as provided by you. I had to retry 5 times for the exception to be raised again - twice. Yesterday, it happened to me on basically every attempt to run the script. Anyhow, here is the log:

```
GET
{'X-RequestStats': 'SDK-Version=python-v1.0.1'}
https://api.onedrive.com/v1.0/drive/items/93778B57A564E317!4847/children
None
None
Unknown Error: Failed to list directory: \Literatur\Conference.Proceedings\LCE2013
> f:\iwu\python_new\onedriveupdate.py(121)getUpItemsList()
    120         L.printL('Unknown Error: Failed to list directory: {0}'.format(dirPath[(len(rootDir)-len(dirPath)):]))
1-> 121         upItemsList= getUpItemsList(upParentDirID, dirPath, attempt+1)
    122     L.printL('List directory: {0} --> {1} pages'.format(dirPath[(len(rootDir)-len(dirPath)):],len(upItemsList)),False)

Trying again.
GET
{'X-RequestStats': 'SDK-Version=python-v1.0.1'}
https://api.onedrive.com/v1.0/drive/items/93778B57A564E317!4847/children
None
None
> f:\iwu\python_new\onedriveupdate.py(122)getUpItemsList()
1   121         upItemsList= getUpItemsList(upParentDirID, dirPath, attempt+1)
--> 122     L.printL('List directory: {0} --> {1} pages'.format(dirPath[(len(rootDir)-len(dirPath)):],len(upItemsList)),False)
    123     return upItemsList

[...]

GET
{'X-RequestStats': 'SDK-Version=python-v1.0.1'}
https://api.onedrive.com/v1.0/drive/items/93778B57A564E317!6564/children
None
None
Unknown Error: Failed to list directory: \papers\04_GCSM 2012\--- Erstellung ---
> f:\iwu\python_new\onedriveupdate.py(121)getUpItemsList()
    120         L.printL('Unknown Error: Failed to list directory: {0}'.format(dirPath[(len(rootDir)-len(dirPath)):]))
1-> 121         upItemsList= getUpItemsList(upParentDirID, dirPath, attempt+1)
    122     L.printL('List directory: {0} --> {1} pages'.format(dirPath[(len(rootDir)-len(dirPath)):],len(upItemsList)),False)

ipdb> 
Trying again.
GET
{'X-RequestStats': 'SDK-Version=python-v1.0.1'}
https://api.onedrive.com/v1.0/drive/items/93778B57A564E317!6564/children
None
None
```

Something else I noticed: While the error occurred for different directory-items most (not all) were situated in the root\Dokumente\Backup\Literatur\Conference.Proceedings\ path of my OneDrive account. Maybe this is of any significance.

Regards,
Stulle

**Comment by cdmayer** [comment] 2016-03-02 18:16
Hello Stulle,
I looked over your code a few times and I can't peg the issue from the information you gave me here. I did notice, though, that your method for paging through the children collection isn't the recommended way. Check out "[Paging Through a Collection](https://github.com/OneDrive/onedrive-sdk-python#paging-through-a-collection)" in the Readme. Specifically, you should be using `collection.next_page_request.get()`.
In addition, make sure you grab the newest version of the SDK (currently 1.0.4) using pip. If you are still having issues after making those changes, come on back.
-Chris

**Comment by Stullemon** [comment] 2016-03-07 17:56
Hey Chris,

I am a bit uncertain. I understood the sample in the way that I should use the last collection (page) to get next collection (page). That would be in pseudo-code: `collection{n} = collection{n-1}.next_page_request.get()`.

Are you suggesting it is actually `collection{n} = collection{0}.next_page_request.get()`?

I will be sure to try a more recent version of the SDK as soon as I get to it.

Regards,
Stulle

**Comment by cdmayer** [comment] 2016-03-07 17:59
What you have in the most recent comment is correct. I must have misread your code.

**Comment by Stullemon** [comment] 2016-03-08 16:24
Hi Chris,

just to let you know: It happened again on a directory/folder with only one page (less than 200 items) and then again twice in a directory with 433 files. I previously downloaded the most recent master of the SDK. 

Prolly one more note: I am using a Windows machine and WinPython 3.4.3.xQt5 (I'd say it's 3.4.3.5 but I cannot be 100 % certain). I'll try getting a more recent version and keep you posted if anything changes.

Regards,
Stulle

**Comment by Stullemon** [comment] 2016-03-08 17:52
Hi again,

So... using a more recent version did not change a thing. WinPython-64bit-3.4.4.1Qt5 also produced an exception on a directory with one page (less than 200 items). I vote for a server- or connection-based error.

Is there anything else I can do to help you guys at Microsoft (not just in the python SDK but also elsewhere) to resolve the issue?

Regards,
Stulle

**Comment by cdmayer** [comment] 2016-03-08 18:28
Yes, there is. I think we need more information about what's going on here. Please follow these steps:
1.  Login to your OneDrive
2.  Go to https://storage.live.com/traceme
3.  Select both the checkboxes in the "AutoFiddler" column
4.  Click on "Start a new trace..." in both rows
5.  Wait for about 1 minute 
6.  Retry the scenario until you get the error
7.  Copy all the information in the table and send it back to me

**Comment by Stullemon** [comment] 2016-03-09 08:32
Hi Chris,

I did like you asked. Here is the information:

```
Type

AutoFiddler

XTraceMe

Path

AzureShare

AzurePath

Expiration

Extend/Remove

Calls I make 
☑ 

☐ 
\93778B57A564E317\2016-03-09_000614  93778B57A564E317\2016-03-09_000614 expired [extend]    [remove] 
Calls against my data 
☑ 

☐ 
\93778B57A564E317\2016-03-09_000546  93778B57A564E317\2016-03-09_000546 expired [extend]    [remove]

```

I started the script on 2016-03-09T09:07:38.897408 (all time stamps are CET) The error occurred between 2016-03-09T09:14:44.048376 and 2016-03-09T09:15:11.006261. The successful retry was completed on 2016-03-09T09:15:17.392586. The path in my drive is `root\Dokumente\{Some Abbreviation}\Literatur\Conference.Proceedings\ASIM_SPL2008\en` (I replaced one directory name for privacy reasons).

I hope it helps. Let me know if there is anything else I could do.

Regards,
Stulle

**Comment by cdmayer** [comment] 2016-03-09 19:03
I looked through your call information. None of the calls appear to fail on the server, and their responses are valid. Something else must be at play here.

I would like to get more information about what you're getting back from the server. Please follow these steps:
- In the same `HttpProvider` file, please add this line in `send`:

``` python

        custom_response = HttpResponse(response.status_code, response.headers, response.text)
        print("Response", response.status_code, response.headers, sep='\n') #Add just this line
        return custom_response
```
- Make sure you also have the lines that gave you before. This way we'll have both the requset and response.
- Send me back the stuff that gets printed to the console for just the request that failed.

I'm sorry it's taking so much effort to debug this. We'll get to the bottom of it!

**Comment by Stullemon** [comment] 2016-03-11 08:20
Hey Chris,

Never mind the effort this takes. I am happy as long as I can help improve things. So, here you go. First my logging:

```
2016-03-11T09:12:49.229516 : Unknown Error: Failed to list directory: \Literatur\Conference.Proceedings\ASIM_SPL2008\Enterprise Dynamics\Movies
2016-03-11T09:12:50.229216 : Trying again.
2016-03-11T09:12:51.220914 : List directory: \Literatur\Conference.Proceedings\ASIM_SPL2008\Enterprise Dynamics\Movies --> 1 pages
```

Now yours:

```
GET
{'X-RequestStats': 'SDK-Version=python-v1.0.4'}
https://api.onedrive.com/v1.0/drive/items/93778B57A564E317!3889/children
None
None
Response
502
{'Date': 'Fri, 11 Mar 2016 08:12:35 GMT', 'X-AsmVersion-ProxyApp': 'UNKNOWN; 19.36.0.0', 'X-ProxyErrorDetail': 'Proxy_GetResponse_ConnectFailure', 'Content-Length': '0', 'Via': '1.1 DM2301____PAP243 (wls-colorado)', 'Server': 'Microsoft-HTTPAPI/2.0', 'X-ClientErrorCode': 'ProxyFail', 'X-WLSPROXY': 'DM2301____PAP243'}

Unknown Error: Failed to list directory: \Literatur\Conference.Proceedings\ASIM_SPL2008\Enterprise Dynamics\Movies
ipdb> Trying again.

GET
{'X-RequestStats': 'SDK-Version=python-v1.0.4'}
https://api.onedrive.com/v1.0/drive/items/93778B57A564E317!3889/children
None
None
Response
200
{'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'X-MSEdge-Ref': 'Ref A: F40DA322CF09415CAA6A92958E2B817B Ref B: E07FBCD9EE0EAD5A55AA2CC05DF481F4 Ref C: Fri Mar 11 00:12:50 2016 PST', 'X-AsmVersion': 'UNKNOWN; 19.36.0.0', 'Server': 'Microsoft-IIS/8.5 Microsoft-HTTPAPI/2.0', 'P3P': 'CP="BUS CUR CONo FIN IVDo ONL OUR PHY SAMo TELo"', 'OData-Version': '4.0', 'Date': 'Fri, 11 Mar 2016 08:12:50 GMT', 'Content-Type': 'application/json; odata.metadata=minimal; odata.streaming=true', 'Content-Length': '1442', 'Via': '1.1 DM2301____PAP099 (wls-colorado)', 'X-MSNSERVER': 'CH3301____PAP226', 'X-WLSPROXY': 'DM2301____PAP099'}
```

I noticed the "Proxy_GetResponse_ConnectFailure"... So I have been trying this from my workstation in the office (which connects through a local proxy) and my private laptop connected to my company network through a Cisco AnyConnect VPN connection. I might have tried this at home when connecting through a cable broadband rooter but I cannot say for sure. Anyhow, I could try that again later today, just let me know.

Regards,
Stulle

**Comment by cdmayer** [comment] 2016-03-11 22:15
Well, I have good news and bad news, depending on how you interpret it. Good news: we have narrowed down the source of the issue. It's our problem, not yours. Bad news: there's nothing you can do right now to make it better; you'll have to wait for us to fix it. Good news: you should be able to just retry the request and see it succeed. I would recommend adding targeted retry logic until we have fixed the issue - retry the request when you see `HTTP 502` with `X-ClientErrorCode: ProxyFail`. That should put a bandage on the issue until we get it fixed on our end.

Thanks for all the help getting us information! I may ask you for more soon, otherwise I'll leave this open until we close the issue on our end.

**Comment by Stullemon** [comment] 2016-03-12 10:39
Hey Chris,

Thank you for the feedback. I'm glad you guys finally found the error. Just let me know as soon as you need more testing, I'll be sure to give it a shot ASAP. Anyhow, judging from your reply - I reckon this is prolly going to take a wee bit. :-)

Regards,
Stulle

**Comment by cdmayer** [comment] 2016-06-28 18:13
Closing because the issue isn't really what's in the title. Also, this isn't an issue with the Python SDK. If this is still occurring, open a similar issue in the [OneDrive API Docs](https://github.com/OneDrive/onedrive-api-docs) repo.

**Closed as completed by cdmayer** 2016-06-28 18:13 UTC
