### ISSUE TITLE
example code. raw_input() is from Python 2

### ISSUE THREAD

**Issue by philshem** [OneDrive/onedrive-sdk-python#165] opened 2019-10-01 09:28 UTC
Regarding this sample code:
https://github.com/OneDrive/onedrive-sdk-python/blob/master/README.md#onedrive

Python3 uses `input()` in place of `raw_input()`

**Comment by KTibow** [comment] 2020-03-16 02:15
Fixed in #174

**Comment by KTibow** [comment] 2020-03-16 02:16
Duplicate of #148

**Comment by baywet** [comment] 2024-10-02 16:59
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information

**Closed as not planned by baywet** 2024-10-02 16:59 UTC
