### ISSUE TITLE
Uploading an item doesn't work when referring to an item by ID

### ISSUE THREAD

**Issue by ybizeul** [OneDrive/onedrive-sdk-python#69] opened 2016-10-28 20:31 UTC
I'm trying to upload big file into and running into the issue where I have to use async methods for this.

I came across #42 but couldn't find a solution to my problem.

Are async operation only compatible with Python 3?

I'm trying to use a stock python from macOS Sierra, and here is what I'm running into :

```
Traceback (most recent call last):
  File "./onedrive.py", line 114, in <module>
    returned_item = client.item(drive='me', id=config['item_id']).children[os.path.basename(upload)].upload_async(upload)
AttributeError: 'ItemRequestBuilder' object has no attribute 'upload_async'
ERROR: Build failed: exit status 1
FATAL: exit status 1                               
```

If I run with python 3.5, small files works, but big files :

```
Traceback (most recent call last):
  File "./onedrive.py", line 114, in <module>
    returned_item = client.item(drive='me', id=config['item_id']).children[os.path.basename(upload)].upload_async(upload)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/onedrivesdk-1.1.6-py3.5.egg/onedrivesdk/version_bridge/fragment_upload.py", line 160, in fragment_upload_async
    session = self.create_session(item).post()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/onedrivesdk-1.1.6-py3.5.egg/onedrivesdk/request/item_create_session.py", line 93, in post
    return self.request().post()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/onedrivesdk-1.1.6-py3.5.egg/onedrivesdk/request/item_create_session.py", line 59, in post
    entity = UploadSession(json.loads(self.send(self.body_options).content))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/onedrivesdk-1.1.6-py3.5.egg/onedrivesdk/request_base.py", line 163, in send
    content=content_dict)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/onedrivesdk-1.1.6-py3.5.egg/onedrivesdk/http_provider.py", line 71, in send
    custom_response = HttpResponse(response.status_code, response.headers, response.text)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/onedrivesdk-1.1.6-py3.5.egg/onedrivesdk/http_response.py", line 59, in __init__
    raise OneDriveError(message["error"], self.status)
onedrivesdk.error.OneDriveError: invalidRequest - API not found
```

What is the requirement to run big files upload?

**Comment by ybizeul** [comment] 2016-10-28 21:16
It looks like it I reference the item by path, it works, not when referenced by ID

**Comment by cdmayer** [comment] 2016-10-31 20:38
Yes async is only compatible with Python 3. You are correct that it only works when accessing by path. That is a bug with the SDK and needs to be fixed.

**Comment by D4N14L** [comment] 2016-11-01 17:43
I'm unable to reproduce. With big files, you may need to use the chunked upload format to send your files to OneDrive. I'm unsure why it would work when referencing by path, but ID should work as long as it's the ID of the parent folder for your uploaded file.

**Comment by D4N14L** [comment] 2016-11-07 22:54
Closing because of lack of repro. If someone can provide instructions for a consistent repro in the future, feel free to re-open.

**Closed as completed by D4N14L** 2016-11-07 22:54 UTC
Labels: bug
